Website_Ban_Giay/thuctap/Controllers/brandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using thuctap.Models;
using PagedList;

namespace thuctap.Controllers
{
    public class brandController : Controller
    {
        // GET: brand
        bangiayDataContext db = new bangiayDataContext();
        public ActionResult Index(int? page)
        {
            //if (Session["admin"] == null)
            //{
            //    return RedirectToAction("Index", "loginAdmin");
            //}
            var brand = from b in db.Brands
                        select b;
            ViewBag.bra = brand;
            ViewBag.brand = brand;

            return View(brand.ToPagedList(page ?? 1, 5));
        }
        [HttpPost]
        public ActionResult Index(int? page, FormCollection a)
        {
            string name = Request["key"];
            var brand = from b in db.Brands
                        where b.Name.Contains(name)
                        select b;
            return View(brand.ToPagedList(page ?? 1, 5));
        }
        public ActionResult Create()
        {
            //if (Session["admin"] == null)
            //{
            //    return RedirectToAction("Index", "loginAdmin");
            //}
            var brand = (from b in db.Brands
                         orderby b.ID descending
                         select b).Take(3);
            return View(brand);
        }
        [HttpPost]
        public ActionResult Create(Brand brand)
        {

            Brand test = db.Brands.Where(p => p.Name == Request["Ten"]).FirstOrDefault();
            ViewBag.date = DateTime.Now;
            if (test != null)
            {
                ViewBag.test = "Hãng " + Request["Ten"] + " đã tồn tại!";
            }
            else
            {
                brand.Name = Request["Ten"];
                brand.Description = Request["MoTa"];
                brand.Image = Request["Anh"];
                brand.created_at = ViewBag.date;
                db.Brands.InsertOnSubmit(brand);
                db.SubmitChanges();
            }

            return this.Create();
        }
        public ActionResult Edit(int id)
        {
            var brand = db.Brands.First(b => b.ID == id);
            return View(brand);
        }
        [HttpPost]
        public ActionResult Edit(int id, Brand brand)
        {
            /*var filename = Request["anh"];*/
            ViewBag.date = DateTime.Now;
            brand = db.Brands.Where(b => b.ID == id).SingleOrDefault();
            brand.Name = Request["Ten"];
            brand.Description = Request["MoTa"];
            brand.Image = Request["logo"];
            brand.updated_at = ViewBag.date;
            /*
            brand.Image = "/Content/Brand/Image/" + GetFileName(file.FileName);*/
            UpdateModel(brand);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var brand = db.Brands.Where(b => b.ID == id).SingleOrDefault();
            db.Brands.DeleteOnSubmit(brand);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit_cre(int id)
        {
            var brand = db.Brands.First(b => b.ID == id);
            return View(brand);
        }
        [HttpPost]
        public ActionResult Edit_cre(int id, Brand brand)
        {
            /*var filename = Request["anh"];*/
            ViewBag.date = DateTime.Now;
            brand = db.Brands.Where(b => b.ID == id).SingleOrDefault();
            brand.Name = Request["Ten"];
            brand.Description = Request["MoTa"];
            brand.Image = Request["logo"];
            brand.updated_at = ViewBag.date;
            /*
            brand.Image = "/Content/Brand/Image/" + GetFileName(file.FileName);*/
            UpdateModel(brand);
            db.SubmitChanges();
            return RedirectToAction("Create");

        }
    }
}

Website_Ban_Giay/thuctap/Views/brand/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/admin.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form thêm hãng</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form thêm hãng</h3>
                </div>
                <form method="post" action="/brand/Create">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>Tên hãng</th>
                                    <th>Mô tả</th>
                                    <th>Logo</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền tên hãng" name="Ten">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền mô tả" name="MoTa">
                                    </td>
                                    <td>
                                        @*<img src="@Model.Image" width="100" height="100" />*@
                                        <input type="text" class="form-control" placeholder="Điền link ảnh" name="Anh">
                                    </td>
                                    <td>
                                        <button type="submit" class="btn btn-primary">Thêm</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
                <h3 style="text-align:center; color:red">@ViewBag.test</h3>
            </div>
            <!-- /.card -->
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header" style="background-color:sandybrown">
                    <h3 class="card-title" style="text-align:center; width:100%">Thông tin 3 hãng được thêm gần nhất</h3>
                </div>
                <div class="card-body">

                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr align="center">
                                <th>Tên hãng</th>
                                <th>Mô tả</th>
                                <th>Logo</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="odd gradeX" align="center">
                                    <td>@item.Name</td>
                                    <td>@item.Description</td>
                                    <td><img src="@item.Image" width="100" height="100" /></td>
                                    <td>
                                        @Html.ActionLink("Sửa", "Edit_cre", new { id = item.ID })
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>


                </div>
            </div>
        </div>
    </div>
</div>

Website_Ban_Giay/thuctap/Views/brand/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/admin.cshtml";
}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form sửa thông tin hãng</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form sửa thông tin hãng</h3>
                </div>
                <form role="form" method="post" action="/brand/Edit/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tên hãng</th>
                                    <th>Mô tả</th>
                                    <th>Logo</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                       @Model.ID
                                    </td>
                                    <td>                                     
                                        <input type="text" class="form-control" placeholder="Điền tên hãng"
                                            name="Ten" value="@Model.Name">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền mô tả"
                                               name="MoTa" value="@Model.Description">
                                    </td>
                                    <td>
                                        @*<input type="file"/>*@
                                        @*<img src="@Model.Image" width="100" height="100" />*@
                                        <input type="text" class="form-control" placeholder="Điền link logo"
                                               name="logo" value="@Model.Image">
                                    </td>

                                    <td>

                                        <button type="submit" class="btn btn-primary">Sửa</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Website_Ban_Giay/thuctap/Views/brand/Edit_cre.cshtml
@{
    ViewBag.Title = "Edit_cre";
    Layout = "~/Views/Shared/admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form sửa thông tin hãng</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form sửa thông tin hãng</h3>
                </div>
                <form role="form" method="post" action="/brand/Edit_cre/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tên hãng</th>
                                    <th>Mô tả</th>
                                    <th>Logo</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                        @Model.ID
                                    </td>
                                    <td>
                                        @Model.Name
                                        <input type="text" class="form-control" placeholder="Điền tên hãng"
                                            name="Ten" value="@Model.Name">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền mô tả"
                                               name="MoTa" value="@Model.Description">
                                    </td>
                                    <td>
                                        @*<input type="file"/>*@
                                        <input type="text" class="form-control" placeholder="Điền link logo"
                                               name="logo" value="@Model.Image">
                                        @*<img src="@Model.Image" width="100" height="100" />*@
                                    </td>
                                    <td>

                                        <button type="submit" class="btn btn-primary">Sửa</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Website_Ban_Giay/thuctap/Views/brand/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/admin.cshtml";
}

@*@using PagedList;
@using PagedList.Mvc;
@model IPagedList<thuctap.Models.Brand>*@
<style>
</style>
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Hãng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Hãng</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

@*
<form class="form-inline ml-3" method="post" action="/brand/Index">
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="searchbar">
                <input class="search_input" type="text" name="key" placeholder="Tìm kiếm">
                <button type="submit" class="btn btn-primary" style="background-color:white; border-color:white; color:blue">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</form>
<br>
*@
<!-- Main content -->
<section class="content">
    <div class="card-body pad">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title" style="text-align:center; width:100%">Bảng hãng</h3>
                    </div>          
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="table" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tên hãng</th>
                                    <th>Mô tả</th>
                                    <th>Logo</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.brand)
                                {
                                    <tr class="odd gradeX" align="center">
                                        <td>@item.ID</td>
                                        <td>@item.Name</td>
                                        <td>@item.Description</td>
                                        <td><img src="@item.Image" width="70" height="70" /></td>
                                        <td>
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                                            @*<i class="fa fa-trash-o" fa-fw></i>@Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                                                <i class="fa fa-pencil fa-fw"></i>@Html.ActionLink("Xóa", "Delete", new { id = item.ID })*@
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tên hãng</th>
                                    <th>Mô tả</th>
                                    <th>Logo</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                        @*<div style="margin-left: 50%;" class="paginate">
                                @Html.PagedListPager(Model, page => Url.Action("Index", "brand", new { page }))
                            </div>*@

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->